### ISSUE TITLE
masterDocument.tex doesn't compile

### ISSUE THREAD

**Issue by siefkenj** [kisonecat/m2o2c2#123]
xelatex nor pdflatex can compile `masterDoucment.tex`.  Is there another way to compile this project into a PDF?

**Comment by bartsnapp** [comment]
Ah - this is an old version. check out:

http://ximera.osu.edu/course/XimeraProject/gettingStarted/

http://ximera.osu.edu/course/mooculus/calculus1

http://ximera.osu.edu/course/mooculus/calculus2

http://ximera.osu.edu/course/mooculus/calculus3

**Comment by siefkenj** [comment]
Thank you, but I cannot figure out how to get the source and compile it to a PDF from the links you provided.

**Comment by bartsnapp** [comment]
First, update your ximeraLatex.cls found here:

https://github.com/XimeraProject/ximeraLatex

(it was updated last Friday)

The source for the courses above are in github:

https://github.com/XimeraProject/gettingStarted

https://github.com/mooculus/

The "course file" is in

https://github.com/mooculus/calculus1/tree/master/mooculus1

https://github.com/mooculus/calculus2/tree/master/mooculus2

https://github.com/mooculus/calculus3/tree/master/mooculus3
